apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ijzk1losu-python
  janus-idp.io/tekton: ijzk1losu-python
  backstage.io/kubernetes-id: ijzk1losu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ijzk1losu-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
