apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ijzk1losu-python-gitops
  description: This is GitOps manifest for ijzk1losu-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ijzk1losu-python
    backstage.io/kubernetes-id: ijzk1losu-python 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: tnevrlka-rhtap/ijzk1losu-python-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ijzk1losu-python
